//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager
{
    public partial class Price
    {
        public int ItemId { get; set; }
        public int StoreId { get; set; }
        public double Price1 { get; set; }
    }
}
